### ISSUE TITLE
showControls doesn't work dynamically

### ISSUE THREAD

**Issue by mqklin** [NuCivic/react-nvd3#11]
I have this component:

    class CommonChart extends React.Component {
      constructor(options) {
        super(options);
        this.state = {show: false};
      }
      onClick = () => {
        this.setState({show: !this.state.show});
      }
      render() {
        return (
          <div>
            <button onClick={this.onClick}>change state</button>
            <span>Show: {""+this.state.show}</span>
            <NVD3Chart showControls={this.state.show} {...this.props}/>
          </div>
        );
      }
    }

After first click on the button `Controls` (`Grouped` and `Stacked`) are showing, but after next click they doesn't disappear.
I'm going to investigate it and to try to fix it.

Related to #4 and #5 

hmm.. I think this is `nvd3` problem

Yes, they just don't remove controls after `showControls` updating. I'm going to create PR there: https://github.com/novus/nvd3/pull/1413

I don't know who have to update Controls -- `react-nvd3` or `nvd3`. 
@topicus , what do you think?

**Comment by topicus** [comment]
I have been out of pocket thia week. Today I am going to take a look at this. Thank you for your help.

**Comment by topicus** [comment]
Seems to be an NVD3 issue: 
- Using showControls directly and calling the update method doesn't change the controls visibility. 
- Using options({showControls: !chart.showControls()}) produce the same behavior you were found in react-nvd3
- Legend component seems to be working in a similar way
- Other parameters works fine

**Comment by mqklin** [comment]
https://github.com/novus/nvd3/pull/1436
