### ISSUE TITLE
Setting up react-nvd3

### ISSUE THREAD

**Issue by royyeah** [NuCivic/react-nvd3#20]
Hi guys,

Sounds like a great library with all the functionality for React in combination with NVD3 I need, but can not manage to set it up and get it working.

Can you help me?
https://jsfiddle.net/x2wuko8g/2/
http://stackoverflow.com/questions/35042621/setting-up-react-in-combination-with-nvd3

Thanks in advance - much appreciated!

Roy

**Comment by topicus** [comment]
@royyeah Check my answer in stackoverflow and let me know if that works for you.

**Comment by royyeah** [comment]
Ha - thought the x and y properties were for the axis labels. Thanks a lot, saved me a lot of work.
