### ISSUE TITLE
slices get broken in pieChart

### ISSUE THREAD

**Issue by paothegit** [NuCivic/react-nvd3#21]
I use filters to update pieChart and slices get broken from time to time. Not sure this is related to nvd3 itself.

I created a dedicated [jsfiddle](https://jsfiddle.net/qkcmcdaw/) to reproduce the issue. When I click "Change Data" button quickly, then slices get broken.

@topicus I'll appreciate if you take a look at this issue and help me with a workaround when you get a chance. Thanks!

**Comment by paothegit** [comment]
@topicus 
More exactly, this occurs when the count of slices reduces (like from 3 to 2).

**Comment by paothegit** [comment]
It seems like nvd3 is okay. Please check my snippet - [jsfiddle](https://jsfiddle.net/69ta5p93/)

**Comment by topicus** [comment]
@paothegit I'll take a look.

**Comment by paothegit** [comment]
@topicus Thanks,  look forward to it!

**Comment by topicus** [comment]
I'll need to implement this to fix this bug https://facebook.github.io/react/docs/animation.html

**Comment by paothegit** [comment]
@topicus 
Thanks for your quick checking.
Will you please let me know this is included in a long-term roadmap or could be a instant fix?

**Comment by topicus** [comment]
I'll implement this in a short term. It isn't an instant fix but shouldn't be a big change.

**Comment by paothegit** [comment]
Great to hear!

**Comment by kylejaster** [comment]
any update on this? would a PR be helpful?

**Comment by topicus** [comment]
I have been pretty busy in the past weeks and I couldn't fix that. @kylejaster If you can create a PR I will review and merge it. If not I will try to fix this on this weekend.

**Comment by topicus** [comment]
Still woking in this. It's not as easy as I thought.

**Comment by paothegit** [comment]
@topicus 
Thank you very much for posting an update, I expect a well-functioning fix(improvement).

**Comment by topicus** [comment]
@paothegit @kylejaster Should be working now. There was tricky because pie charts doesn't dispatch renderEnd events from the chart itself but from an internal component called pie. So far, that's the only chart I've found that isn't dispatching from the chart itself.

**Comment by kylejaster** [comment]
thanks @topicus - sorry i never got around to this - we'll incorporate.

**Comment by paothegit** [comment]
Thanks for your hack! @topicus 

I confirm that it's working seamlessly [here](https://jsfiddle.net/qkcmcdaw/2/)

**Comment by topicus** [comment]
Awesome, closing this then.
