### ISSUE TITLE
update npm package

### ISSUE THREAD

**Issue by mqklin** [NuCivic/react-nvd3#22]
`package.json` in npm package doesn't contain last `nvd3` version, still `github:novus/nvd3#5992b889c6ce8e108d42b73c6382c8863980e34a`. @topicus , can you update it, please?

**Comment by topicus** [comment]
I'll update as soon as I figure out https://github.com/NuCivic/react-nvd3/issues/21

**Comment by topicus** [comment]
@mqklin Should be updated now. Please check this.

**Comment by mqklin** [comment]
I'll check at the weekend

**Comment by mqklin** [comment]
Sorry, I couldn't check it, because I fired.
I see that now the version is 1.8.2
