### ISSUE TITLE
ERROR in v0.5.0+ nvd3 multiChart.dispatch does not have renderEnd

### ISSUE THREAD

**Issue by tarunc** [NuCivic/react-nvd3#28]
`d3.dispatcher` complains because react-nvd3 (in v0.5.0+) uses the `.dispatch` property to detect the  `'renderEnd'` event on nvd3 chart models. However, several nvd3 charts do not feature the `'renderEnd'` event. 

I found 2 charts:
multiChart: https://github.com/novus/nvd3/blob/master/src/models/multiChart.js#L51
linePlusBarChart: https://github.com/novus/nvd3/blob/master/src/models/linePlusBarChart.js#L44

**Comment by topicus** [comment]
@tarunc working to fix this.

**Comment by topicus** [comment]
@tarunc Should be fixed now. Update to 0.5.2.

**Comment by topicus** [comment]
BTW thank you for reporting this.

**Comment by tarunc** [comment]
@topicus Works like a charm! Thanks for fixing the issue quickly!
