### ISSUE TITLE
add callback for nv.addGraph

### ISSUE THREAD

**Issue by benzitohhh** [NuCivic/react-nvd3#3]
Hi there,

this library is so useful. Thanks for all the hard work.

But how can a callback be registered with `nv.addGraph`?

i.e.

`nv.addGraph` can take a callback argument: https://github.com/novus/nvd3/blob/master/src/core.js#L114

```javascript
    nv.addGraph(<generate Function>, <callback Function>)
```

This callback can can be used for extending the functionality of an nvd3 chart. It is a crucial part of the project that I am working on.

As far I can see there is no way to pass this in react-nvd3.

Perhaps it could be exposed as a param?

**Comment by topicus** [comment]
Great feedback, I will add it as a component property.

**Comment by benzitohhh** [comment]
Ok amazing - thanks!

**Comment by topicus** [comment]
I've added the callback in the last fix. You can pass it in this way:

```<NVD3Chart renderEnd={callback} .../>```

Let me know if it works for you.

**Comment by benzitohhh** [comment]
@topicus yup it works great - thanks a lot.
