### ISSUE TITLE
Update npm version with latest

### ISSUE THREAD

**Issue by ccastarivale** [NuCivic/react-nvd3#32]
Looks like [this latest commit](https://github.com/NuCivic/react-nvd3/commit/1e6f3eea7f7322b3e103b493c598d187e27134b6) hasn't made it into npm. Would you update it?

**Comment by topicus** [comment]
@ccastarivale  Thanks for you noticing that. I'll update ASAP.

**Comment by topicus** [comment]
@ccastarivale I've just updated the npm version.
