### ISSUE TITLE
Support for React v15

### ISSUE THREAD

**Issue by jharris4** [NuCivic/react-nvd3#35]
It'd be nice if react-nvd3 was updated to support React v.15.

Should be as simple as changing the version package.json as there were no deprecation warnings with v0.0.14

**Comment by topicus** [comment]
@jharris4 Thanks for reporting that. I just merged a PR from @nozaq which fix that. Please review and let me know if you have any other issue.

**Comment by jharris4** [comment]
Looks good to me, can you release a new version?

**Comment by topicus** [comment]
@jharris4 Sorry I forgot to publish it. It's done. Please try again.
