### ISSUE TITLE
I believe React should be in peerDependencies

### ISSUE THREAD

**Issue by stkrzysiak** [NuCivic/react-nvd3#36]
Hi, 
First, thank your for putting this module together, it looks very promising.  I was hoping to test it out this evening and ran into a error like this:
`Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

Sure enough react-nvd3 has a dependency on react, and apparently this is what peerDependencies are for, so I tested this out and it works just fine then.  Any objections to a PR?  Or if someone beats me to it, have at it.

**Comment by topicus** [comment]
@stkrzysiak Thanks for note this. It should be fixed now. Please update to 0.5.6 and let me know if it's working for you.

**Comment by stkrzysiak** [comment]
Looks like it's working fine, thanks.
