### ISSUE TITLE
pieChart example is not working

### ISSUE THREAD

**Issue by tao-findly** [NuCivic/react-nvd3#38]
Hi, 

I just clone the v0.5.7 source code and run the charts examples. When I was running the pieChart example in Chrome, I got follow error in the console and the chart not render properly:

d3.min.js:1 Error: Invalid value for <g> attribute transform="translate(NaN,NaN)"

Other charts examples work fine.

Is this a bug for the pieChart?

Cheers,

**Comment by topicus** [comment]
@tao-findly Sorry about the delay and thanks for notice that. It should be fixed in the master branch.

**Comment by topicus** [comment]
Closing this, reopen if the bug persists.

**Comment by verdan** [comment]
@topicus I'm still seeing the error
```console
Error: <g> attribute transform: Expected number, "translate(NaN,NaN)".
```

**Comment by topicus** [comment]
@verdan Try using master branch. I want to fix other issues before publish to npm.

**Comment by verdan** [comment]
@topicus still same issue. I've doubled check that I have your recent commit that you did in the example and yes, I have the latest master branch. 
```console
6d3.js:670 Error: <g> attribute transform: Expected number, "translate(NaN,NaN)".
```

**Comment by verdan** [comment]
here is my code.
```javascript
		<NVD3Chart type="pieChart" datum={dataList} x="label" y="value" showLegend={true} showControls={false}  tooltip={{enabled: true}} height={370} />
```

**Comment by topicus** [comment]
@verdan Just to clarify, Is the pieChart example (inside the example folder) not working? 

To check why your code is not working I need the datum example (a sample if it's big).

Remember label and value should be keys inside each object of the datum list. I.e:

```javascript
let dataList = [
  { label: 'My label', value: 12},
  { label: 'My label2', value: 12},
  { label: 'My label3', value: 16}
];
```
