### ISSUE TITLE
Ability to pass key function

### ISSUE THREAD

**Issue by jscheid** [NuCivic/react-nvd3#39]
Hi, thanks for this great little project, works really well!

I'd like to use a key function in order to achieve [object constancy](https://bost.ocks.org/mike/constancy/). I don't see a way to do this with react-nvd3, is there a workaround? I think basically react-nvd3 would need to call `data` instead of `datum` and allow passing a second argument.

**Comment by topicus** [comment]
@jscheid I'm not 100% sure what are you trying to achieve but I don't think you need to worry about that with nvd3 since when you change the data automatically figure out how to preserve and animate elements. If you change the datum array it just works. 

However if it's not working for you, could provide me a code example? It could help me to figure out what's happening.

**Comment by jscheid** [comment]
Hi @topicus, sorry for the tardy reply. My problem is not that I need nvd3 to preserve the elements, rather it's that I want to control the color of elements regardless of their order. For example, say sometimes the graph renders with elements A, B, C but sometimes A is missing and only B and C are rendered. I would then like B and C have the same colors (i.e. skip the color for A).

I've found a way to do this, which is to set the `color` option to a function that converts the label to a color. However this is a bit awkward, because at that point the label has already be run through i18n. If you don't want to implement this feature then this workaround will do, but I think it would be cleaner if there was the ability to assign a key to the data. Or perhaps there is an alternative approach that I'm missing?

**Comment by jscheid** [comment]
I have a good solution now, which is to set colors directly in the data. I don't know why I didn't see this option earlier, it's the most straightforward one. Sorry for the noise, I'm closing this.

**Comment by topicus** [comment]
@jscheid  Good solution! Sorry I didn't answer, I've been pretty slammed this week.
