### ISSUE TITLE
configure not called onComponentDidUpdate

### ISSUE THREAD

**Issue by benzitohhh** [NuCivic/react-nvd3#4]
At the moment, `this.props.configure` is only called onComponentDidMount.

It is not called onComponentDidUpdate.

This is a problem in a project I am working on. For example, we want to change the colour scheme on an update.

**Comment by topicus** [comment]
@benzitohhh I've pushed a fix. Let me know if that solves your issue.

**Comment by benzitohhh** [comment]
@topicus it works great - thanks so much.
