### ISSUE TITLE
Customize tooltip header

### ISSUE THREAD

**Issue by eversadia** [NuCivic/react-nvd3#42]
Hi,
Is there an option to customize the tooltip header value. Right now the x axis is rendering time, and the tooltip header is showing the x axis value. What i want is to append the the Y-M-D before the original tooltip header. Is that possible

**Comment by topicus** [comment]
@eversadia I didn't tried it but this should work:
```
function custom_template_function(obj){
return '<h3>'.obj.label.'</h3>';
}

<AnyChart tooltip={{contentGenerator: custom_template_function}}.../>
```

Let me know if this approach works for you.

**Comment by eversadia** [comment]
Hi,
function custom_template_function(obj){
return <h3>{obj.label}</h3>
}

<NVD3Chart type="lineChart"  tooltip={{contentGenerator: custom_template_function}} ... />

Its not working.. I'm using a lineChart.
Thanks.

**Comment by eversadia** [comment]
Already got it, I use configure props

**Comment by IncubatedChun** [comment]
@eversadia  could you give me some details how to do this? I have the same problem now.

**Comment by eversadia** [comment]
@IncubatedChun

Here is the examples, just disregard the other part... look for the configure.

`let  datas = {
        type: 'lineChart',
        datum: collection,
        xAxis: {
          tickFormat: function ( d ) {
            if( xFormat == 'hour' )
              return d3.time.format( '%H:%M' )( new Date( d ) )
            else if( xFormat == 'dayhour' )
              return d3.time.format( '%m-%d %H:%M' )( new Date( d ) )
            else if( xFormat == 'day' )
              return d3.time.format( '%m-%d' )( new Date( d ) )
          },
          axisLabel: ''
        },
        yAxis: {
          tickFormat: function ( d ) {
            return d
          },
          axisLabel: ''
        },
        x: function ( d ) {

          let parseDate = d3.time.format( "%YM%mD%dT%HG%MS%S" ).parse
          let date = parseDate( d.x )

          return date
        },
        y: 'value',
        duration: 100,
        height: 500,
        interactive: true,
        margin: {
          right: 50
        },
        transitionDuration: 0,
        useInteractiveGuideline: true,
        xScale: d3.time.scale(),
        forceY: [ 0 ],
        configure: function ( chart ) {

          let niceFormat = d3.time.format( '%Y-%m-%d %H:%M' )
          let contentGenerator = chart.interactiveLayer.tooltip.contentGenerator()
          let tooltip = chart.interactiveLayer.tooltip

          tooltip.contentGenerator( function ( d ) {
            d.value = d.series[ 0 ].data.x;
            return contentGenerator( d );
          } )

          tooltip.headerFormatter( function ( d ) {
            let parseDate = d3.time.format( "%YM%mD%dT%HG%MS%S" ).parse
            let date = parseDate( d )

            date = niceFormat( date )
            return date
          } );
          return chart
        }
      }

     <NVD3Chart id="lineChart"  { ...datas } />`
