### ISSUE TITLE
Quickstart renders only blank pages:  ReferenceError: React is not defined

### ISSUE THREAD

**Issue by hexatonics** [NuCivic/react-nvd3#44]
Followed quickstart procedure from bottom README file.  Tested on OS X 10.10.5 in Chrome, Safari, and Firefox.  All examples show up as blank. 

JS Error is:

`TypeError: _react2.default is undefined
<anonymous>
 react-nvd3.js:287
__webpack_require__()
 react-nvd3.js:30
<anonymous>
 react-nvd3.js:50
<anonymous>
 react-nvd3.js:11
webpackUniversalModuleDefinition()
 react-nvd3.js:9
<anonymous>
 react-nvd3.js:1
 react-nvd3.js:287:1`

**Comment by topicus** [comment]
Thank you for reporting this. WIP.

**Comment by topicus** [comment]
@hexatonics I just updated the quick start code. You can take a look at changes here https://github.com/NuCivic/react-nvd3/commit/867c7e1a6c0148a91f01753a5ea01901b727bb90 

Please reopen if this didn't work for you.
