### ISSUE TITLE
Bullet chart transitions not working

### ISSUE THREAD

**Issue by acasaccia** [NuCivic/react-nvd3#50]
Bullet chart transitions seem to be not working https://jsfiddle.net/acasaccia/69z2wepo/54773/.
The bar chart in the fiddle animates correctly while the bullet chart doesn't.

The d3 implementation should support animation as can be seen on https://bl.ocks.org/mbostock/4061961

I'd be glad to contribute a fix for this. Is this a known probem? Any ideas of where to start from?

**Comment by acasaccia** [comment]
Looks like the bulletChart nvd3 implementation has some problems.

In /nvd3/examples/bulletChart.html the animations for ranges, measures and markers are not working even though in the scale is animated.

I'll make my way through nvd3  and eventually reopen this if a fix is needed.

**Comment by topicus** [comment]
@acasaccia Thank you very much for reporting that. Keep me posted about this nvd3 issue.

**Comment by acasaccia** [comment]
I made this pull request that implements transitions https://github.com/novus/nvd3/pull/1802. Unfortunately a couple of tests are broken because of the animations. Not sure if and when I'll have time to investigate how to fix them.

**Comment by acasaccia** [comment]
@topicus also I forgot to mention that I tried react-nvd3 with my fix on the nvd3 repo and it works perfectly. So I confirm it's definetely not a react-nvd3 issue!
