### ISSUE TITLE
Linechart

### ISSUE THREAD

**Issue by SubhuMS** [NuCivic/react-nvd3#52]
How to add labels and markers for points in the LineChart.

**Comment by topicus** [comment]
@SubhuMS No sure what you mean with labels and markers. Could you provide more information about what are you trying to do?

**Comment by SubhuMS** [comment]
Hi @topicus ,  i tried to dispalay a line chart as attached here, is there any option to display the label for each plot in the line chart?
![linechart](https://cloud.githubusercontent.com/assets/17092786/18261841/e612ca26-7419-11e6-8900-778a6c45d58f.jpg)

**Comment by topicus** [comment]
@SubhuMS Sadly NVD3 doesn't provide such feature. However you can play with the renderEnd callback and some d3 manipulation to achieve the desired result.

**Comment by SubhuMS** [comment]
@topicus  thanks topicus, i tried adding text tags once the Linechart rendered in Dom. It worked out :)
