### ISSUE TITLE
Tooltip legened displayed separately for every series

### ISSUE THREAD

**Issue by atais** [NuCivic/react-nvd3#61]
**Plunker:** https://plnkr.co/edit/2UT2UO

**Description:**
Hovering over the series should show a tooltip with values in given point. It does, but values are shown only for single series. Moving cursor up or down a little shows the other series.

**Expected:**
Tooltip should present all data in the given point at one time (screen from angular app):
![screenshot_2017-01-13_14-05-57](https://cloud.githubusercontent.com/assets/1538192/21931063/a8aee80a-d999-11e6-9b80-1abbf6ffff8f.png)

**Comment by atais** [comment]
I was missing `useInteractiveGuideline={true}` :disappointed: 

works OK with fix:
```javascript
 <NVD3Chart type="lineChart" datum={series} x="x" y="y"
                    useInteractiveGuideline={true}
                    containerStyle={{ height: "500px" }}/>  
```

**Comment by topicus** [comment]
@atais Awesome, I'll work on fixing the examples you pointed out in #60
