### ISSUE TITLE
Does d3 need to be a global?

### ISSUE THREAD

**Issue by ttrmw** [NuCivic/react-nvd3#7]
It appears that d3 needs to be a global for react-nvd3 to work, is there any way around this? I was hoping to use

```js
var d3 = require("d3");
var NVD3Chart = require("react-nvd3");
```

but this does not work.

**Comment by topicus** [comment]
Working in this. I still trying to figure out how to make it work.

**Comment by ttrmw** [comment]
I observe that the nvd3 module also seems to require that d3 is a global when used in this manner

**Comment by topicus** [comment]
Since nvd3 needs d3 as global I don't know if there is a way to make this work. Do you have any clue?

**Comment by mqklin** [comment]
@ttrmw @topicus 
Look at this PR: https://github.com/novus/nvd3/pull/1389
I've added this lines to `nv.d3.js` file in `react-nvd3/node_modules/nvd3/build` folder:

    var d3;
    if (typeof(module) !== 'undefined' && typeof(exports) !== 'undefined' && typeof(d3) == 'undefined') {
        d3 = require('d3');
    }

It works for me, but i believe we shoudn't patch `react-nvd3` in this manner. 
All that we can do -- just wait for `nvd3` will support this feature.

**Comment by SylarRuby** [comment]
This needs fixing

**Comment by topicus** [comment]
@SylarRuby I've been pretty slammed the past weeks. I'm going to be able to take a look at this by the end of this week. Any PR is welcome.

**Comment by topicus** [comment]
@ttrmw @SylarRuby I did some discovery about this and it seems like using the @mqklin nvd3 patch worked. We need to wait until nvd3 folks merge this PR novus/nvd3#1389

After that merge you'll able to do:

```javascript
var reactNVD3 = require('react-nvd3');
```

In this way you won't need to load d3 separately.

**Comment by topicus** [comment]
@ttrmw @SylarRuby it seems like this is already fixed in the nvd3 library. Please check that.

**Comment by mqklin** [comment]
@topicus https://github.com/NuCivic/react-nvd3/pull/19

**Comment by topicus** [comment]
@mqklin This seems to be already addressed by the nvd3 folks. Closing this.

https://github.com/novus/nvd3/issues/1404
