### ISSUE TITLE
tooltip "confused" about location after legend toggle 

### ISSUE THREAD

**Issue by grahambryan** [NuCivic/react-nvd3#79]
Hello, I am currently working with the Line graph example. 

Problem: 
Tooltip behaves correctly at start 
![screen shot 2017-08-16 at 9 10 10 am](https://user-images.githubusercontent.com/29125497/29367648-3b4b64be-8263-11e7-82ce-690c60103bbf.png)

Then once I toggle the legends and turn them both back on, this happens

![screen shot 2017-08-16 at 9 09 40 am](https://user-images.githubusercontent.com/29125497/29367662-46f73aae-8263-11e7-8b0f-75ae32aead81.png)

Has anyone seen this before? 

`React.createElement(NVD3Chart, {
            xAxis: {
              tickFormat: function(d){ return d; },
              axisLabel: 'Period'
            },
            yAxis: {
              tickFormat: function(d) {return parseFloat(d).toFixed(2); },
              axisLabel: 'Values'
            },
            title: 'RPY',
            type:'lineChart',
            datum: data, 
            x: 'label',
            y: 'value',
            duration: 1000,
            margin: {
              left: 160
            },
            focusEnable: true, 
            height: 500,
            useInteractiveGuideline: true,
            renderEnd: function(){
              console.log('renderEnd');
            }
          })`

**Comment by topicus** [comment]
This is a weird one. I will need to take a look.

**Comment by grahambryan** [comment]
Any updates on this?

**Comment by grahambryan** [comment]
ended up being a render issue on my end.
