### ISSUE TITLE
expose legend and tooltip

### ISSUE THREAD

**Issue by benzitohhh** [NuCivic/react-nvd3#8]
Currently legend and tooltip are not exposed.

It would be great if they could be exposed as per the yAxis and xAxis. So then they could be accessed like this:
```javascript
      <NVD3Chart
        type={'lineChart'}
        tooltip={{ keyFormatter: someFn }}
        legend={{ key: someOtherFn }}
      />
    );
```

As far as I can see, right now the only way to access them is via the configure function:
```javascript
    function configure(chart) {
      chart.tooltip.keyFormatter(someFn);
      chart.legend.key(someOtherFn);
    }

      <NVD3Chart
        type={'lineChart'}
        configure={configure}
      />
```

This is really awkward, as it makes overriding defaults difficult.

**Comment by topicus** [comment]
This should be easy to do. I'll work on this.

**Comment by benzitohhh** [comment]
thanks @topicus - much appreciated

**Comment by mwhite** [comment]
What would be really awesome is creating a factory for individual chart types, where propTypes is dynamically defined by inspecting the nvd3 `chart._options` object for top-level props, and all properties of an nvd3 `chart` are automatically filtered to find chart sub-components, which have an automatically defined React.PropTypes.shape prop.

**Comment by mwhite** [comment]
It would also be nice to have separate react chart components for each top-level chart for readability.

**Comment by topicus** [comment]
@mwhite Yes, I think that's a good architecture. I will work on that. In the meantime I'm going to push a quick fix to make folks able to configure tooltips and legends.

**Comment by topicus** [comment]
@benzitohhh Now you can configure nested components in the way you proposed:
```
<NVD3Chart tooltip={{enabled: true}} ...../>
```

Please let me know if it worked for you.

More details baf0803d36f6d87735e2c58c36289b9f6732deee

**Comment by benzitohhh** [comment]
Thanks @topicus - this works great now!

**Comment by topicus** [comment]
Closing this.

**Comment by mqklin** [comment]
@topicus, how can I configure legend margin without `configure` prop?
Now I do this: `<NVD3Chart  configure={chart => chart.legend.margin({bottom: 50})}/>`
But I want something like this: `<NVD3Chart legend={margin({bottom: 50})}/>` but it's not working.
