### ISSUE TITLE
Use the latest nvd3 source.

### ISSUE THREAD

**Issue by ovvn** [NuCivic/react-nvd3#9]
The npm module was published 6 months ago. It makes sense to use the latest api in order to utilize new chart components parameters. So I think it makes sense to update 'nvd3' deps to take source from github master branch rather than npm.

**Comment by topicus** [comment]
I've updated the nvd3 version to the last commit. It's the only way I've found to prevent a broken version after an nvd3 update. 

Thank you for your help.

**Comment by ovvn** [comment]
It works, thank you.
